apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base
  - hpa.yaml
  - network-policy.yaml

patches:
  - path: patch-deployment.yaml

images:
  - name: nginx
    newTag: "1.25"

commonLabels:
  environment: production