apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-primary
  labels:
    app: sample-app
spec:
  replicas: 9
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
        version: v1.0.0
    spec:
      containers:
      - name: app
        image: nginx:1.25
        ports:
        - containerPort: 80