apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

resources:
  - ../../base

patches:
  - path: patch-deployment.yaml
  - path: configmap.yaml

images:
  - name: nginx
    newTag: "1.25"

commonLabels:
  environment: development