apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-blue
  labels:
    app: sample-app
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
      version: blue
  template:
    metadata:
      labels:
        app: sample-app
        version: blue
    spec:
      containers:
      - name: app
        image: nginx:1.25
        ports:
        - containerPort: 80